name: CI

on:
  push:
    branches: [ devel, main, master, RELEASE_* ]
  pull_request:
    branches: [ devel, main, master, RELEASE_* ]

jobs:
  check:
    uses: lwaldron/workflows/.github/workflows/bioccheck.yml@main
    with:
      enable_pkgdown: false
      error_on: 'error'
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
